#
# https://github.com/P3TERX/Actions-OpenWrt
#
# File: .github/workflows/openwrt-bulder.yml
# Description: Build OpenWrt using GitHub Actions
#
# Copyright (c) 2019-2024 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Clear server space

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Clear server space
      id: clean
      if: always()
      run: |
        # Clean up server space
      
        rm -rf $(ls . | grep -v "^output$" | xargs) 2>/dev/null
        ls /
        printf 'ls /usr -l'
        ls /usr -l
        # printf 'ls /usr/bin -l'
        # ls /usr/bin -lhtR
        cd /usr
        du  /usr -lh  --max-depth=1 # | sort -nr | head -n 10
       

  
    - name: Check space usage
      if: (!cancelled())
      run: df -hT
